//! Tier-1 findings sharing (M8, user idea 2026-08-26): a sanitized
//! markdown bundle of this machine's measured results — hardware, build,
//! measurement tables, trial verdicts, build-over-build history — written
//! LOCALLY for the user to review and post where maintainers and quant
//! authors actually look (llama.cpp discussions, model repos).
//!
//! The standing rule this module exists under: the app never transmits
//! anything. Outbound sharing is opt-in, human-reviewed, and manually
//! performed by the user with this file in hand.

use crate::core::advisor::UpstreamStatus;
use crate::core::history;
use crate::core::router::Measurements;
use crate::core::trial::{self, Trials};

/// Everything the renderer needs, gathered by the caller — pure inputs so
/// the sanitization and layout are unit-testable.
pub struct ReportInputs<'a> {
    /// YYYY-MM-DD, from `date_from_epoch`.
    pub date: String,
    pub os: String,
    pub ram_mib: u64,
    /// Physical GPUs, deduped across backend views.
    pub gpus: Vec<crate::core::discover::PhysicalGpu>,
    /// Binary build serving right now.
    pub build: Option<u64>,
    pub upstream: Option<&'a UpstreamStatus>,
    pub measurements: &'a Measurements,
    pub trials: &'a Trials,
    pub history: &'a [history::Entry],
    /// The user's home directory, for path sanitization.
    pub home: Option<String>,
}

/// Civil date from unix seconds (Howard Hinnant's algorithm) — no chrono
/// dependency for one timestamp.
pub fn date_from_epoch(secs: u64) -> String {
    let days = (secs / 86_400) as i64;
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    format!("{y:04}-{m:02}-{d:02}")
}

/// Strip machine-identifying strings: the home directory becomes `~`
/// (failure strings can embed full model paths).
fn sanitize(s: &str, home: Option<&str>) -> String {
    match home {
        Some(h) if !h.is_empty() => s.replace(h, "~"),
        _ => s.to_string(),
    }
}

pub fn render(i: &ReportInputs) -> String {
    let mut out = String::new();
    let push = |out: &mut String, s: String| {
        out.push_str(&s);
        out.push('\n');
    };
    push(&mut out, format!("# Local llama.cpp field findings — {}", i.date));
    push(
        &mut out,
        "\nGenerated by modelsteward. Every number below is measured on the \
         machine described — settled context after `--fit`, server-timed \
         generation, llama-bench baselines — not estimated. Shared by the \
         machine's owner after review; paths are sanitized."
            .to_string(),
    );

    push(&mut out, "\n## Machine".to_string());
    for g in &i.gpus {
        if g.shared_memory {
            push(
                &mut out,
                format!(
                    "- iGPU: {} (shared system memory — not used for serving, not \
                     counted as VRAM)",
                    g.name
                ),
            );
        } else {
            push(
                &mut out,
                format!(
                    "- GPU: {} — {} MiB usable (backend views: {})",
                    g.name,
                    g.vram_mib,
                    g.ids.join(", ")
                ),
            );
        }
    }
    push(&mut out, format!("- RAM: {} MiB", i.ram_mib));
    push(&mut out, format!("- OS: {}", i.os));
    match i.build {
        Some(b) => push(&mut out, format!("- llama.cpp build: b{b}")),
        None => push(&mut out, "- llama.cpp build: unknown".to_string()),
    }
    if let Some(u) = i.upstream
        && let Some(up) = u.upstream_build
    {
        push(&mut out, format!("- upstream at last check: b{up}"));
    }

    push(&mut out, "\n## Measured models".to_string());
    push(
        &mut out,
        "| model | settled ctx | pp t/s | tg t/s | tool calls | bench build |".to_string(),
    );
    push(&mut out, "|---|---|---|---|---|---|".to_string());
    let mut failures: Vec<(String, String)> = Vec::new();
    for (id, m) in i.measurements {
        if let Some(err) = &m.error {
            failures.push((id.clone(), sanitize(err, i.home.as_deref())));
            continue;
        }
        let Some(ctx) = m.n_ctx else { continue };
        let f = |v: Option<f64>| v.map(|x| format!("{x:.0}")).unwrap_or_else(|| "—".into());
        push(
            &mut out,
            format!(
                "| {id} | {ctx} | {} | {} | {} | {} |",
                f(m.pp_tps),
                f(m.tg_tps),
                match m.tool_call {
                    Some(true) => "yes",
                    Some(false) => "no",
                    None => "?",
                },
                m.bench_build
                    .map(|b| format!("b{b}"))
                    .unwrap_or_else(|| "—".into()),
            ),
        );
    }
    if !failures.is_empty() {
        push(&mut out, "\n### Known load failures".to_string());
        for (id, err) in failures {
            push(&mut out, format!("- {id}: {err}"));
        }
    }

    push(&mut out, "\n## Trial verdicts (config A/B, server-timed)".to_string());
    let mut any = false;
    for (model, table) in i.trials {
        for menu in ["spec", "ub", "kv"] {
            let Some(r) = trial::stored_report(menu, table) else {
                continue;
            };
            any = true;
            push(&mut out, format!("- {model} · {menu}: {}", r.verdict.reason));
            for nm in &r.near_misses {
                push(
                    &mut out,
                    format!("  - rejected tradeoff: {} — {} for {}", nm.label, nm.gain, nm.cost),
                );
            }
        }
    }
    if !any {
        push(&mut out, "(no trials recorded)".to_string());
    }

    // Build-over-build shifts a maintainer would want to know about.
    push(&mut out, "\n## Build-over-build history".to_string());
    if let Some(line) = history::build_advisory(i.history) {
        push(&mut out, format!("**Rebuild scorecard:** {line}"));
        push(&mut out, String::new());
    }
    let mut any = false;
    let mut by_model: std::collections::BTreeMap<&str, Vec<&history::Entry>> = Default::default();
    for e in i.history {
        by_model.entry(&e.model).or_default().push(e);
    }
    for (model, entries) in by_model {
        // Latest ctx and tg per build, oldest build first.
        let mut ctx_by_build: std::collections::BTreeMap<u64, u64> = Default::default();
        let mut tg_by_build: std::collections::BTreeMap<u64, f64> = Default::default();
        for e in entries {
            if let (Some(b), Some(c)) = (e.build, e.n_ctx) {
                ctx_by_build.entry(b).or_insert(c);
            }
            if let (Some(b), Some(t)) = (e.build, e.tg_tps) {
                tg_by_build.entry(b).or_insert(t);
            }
        }
        if ctx_by_build.len() > 1 {
            any = true;
            let line: Vec<String> = ctx_by_build
                .iter()
                .map(|(b, c)| format!("b{b}: {c}"))
                .collect();
            push(&mut out, format!("- {model} settled ctx — {}", line.join(" -> ")));
        }
        if tg_by_build.len() > 1 {
            any = true;
            let line: Vec<String> = tg_by_build
                .iter()
                .map(|(b, t)| format!("b{b}: {t:.0} t/s"))
                .collect();
            push(&mut out, format!("- {model} generation — {}", line.join(" -> ")));
        }
    }
    if !any {
        push(
            &mut out,
            "(single-build history so far — shifts appear after the next rebuild)".to_string(),
        );
    }
    out
}

/// The machine-readable twin of the markdown report — same sanitized
/// inputs, serialized whole so a future ingestion home (sharing tier 2)
/// needs no format work. Written alongside as findings-report.json.
#[derive(serde::Serialize)]
struct FindingsJson<'a> {
    generator: &'static str,
    date: &'a str,
    os: &'a str,
    ram_mib: u64,
    gpus: &'a [crate::core::discover::PhysicalGpu],
    llamacpp_build: Option<u64>,
    upstream_build: Option<u64>,
    measurements: &'a Measurements,
    trials: &'a Trials,
    history: &'a [history::Entry],
}

/// Gather this machine's data, render, and write BOTH report files
/// (markdown for humans, JSON for machines). Returns the markdown path.
/// The caller shows it to the user — nothing is sent.
pub fn generate(cfg: &crate::core::settings::AppConfig) -> anyhow::Result<std::path::PathBuf> {
    use crate::core::{advisor, discover, router, rows, system};
    let scan = system::scan_report(cfg, &[]);
    let dir = router::state_dir();
    let upstream = advisor::read_upstream_status(&dir);
    let home = std::env::home_dir().map(|h| h.display().to_string());
    // Sanitize ONCE, at the source, so both output formats inherit it —
    // error strings are where filesystem paths hide.
    let mut measurements = router::read_measurements(&dir);
    for m in measurements.values_mut() {
        if let Some(e) = &m.error {
            m.error = Some(sanitize(e, home.as_deref()));
        }
    }
    let mut hist = history::read_all(&dir);
    for e in &mut hist {
        if let Some(err) = &e.error {
            e.error = Some(sanitize(err, home.as_deref()));
        }
    }
    let trials = trial::read_trials(&dir);
    let inputs = ReportInputs {
        date: date_from_epoch(advisor::now_epoch()),
        os: format!("{} {}", std::env::consts::OS, std::env::consts::ARCH),
        ram_mib: rows::read_ram_mib(),
        gpus: discover::physical_gpus(&scan.devices),
        build: system::env_build(&scan),
        upstream: upstream.as_ref(),
        measurements: &measurements,
        trials: &trials,
        history: &hist,
        home,
    };
    let json = FindingsJson {
        generator: "modelsteward",
        date: &inputs.date,
        os: &inputs.os,
        ram_mib: inputs.ram_mib,
        gpus: &inputs.gpus,
        llamacpp_build: inputs.build,
        upstream_build: inputs.upstream.and_then(|u| u.upstream_build),
        measurements: inputs.measurements,
        trials: inputs.trials,
        history: inputs.history,
    };
    std::fs::write(
        dir.join("findings-report.json"),
        serde_json::to_string_pretty(&json)?,
    )?;
    let text = render(&inputs);
    let path = dir.join("findings-report.md");
    std::fs::write(&path, text)?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::router::Measurement;

    #[test]
    fn report_sanitizes_and_covers_sections() {
        let mut m = Measurements::new();
        m.insert(
            "qwen3.8-27b-ud-q4_k_xl".into(),
            Measurement {
                n_ctx: Some(118_016),
                tool_call: Some(true),
                pp_tps: Some(1462.7),
                tg_tps: Some(40.6),
                bench_build: Some(10_630),
                ..Default::default()
            },
        );
        m.insert(
            "broken".into(),
            Measurement {
                error: Some("error loading model '/home/buck/models/x.gguf'".into()),
                ..Default::default()
            },
        );
        let trials = Trials::new();
        let hist = vec![
            history::Entry {
                when: 1,
                model: "qwen3.8-27b-ud-q4_k_xl".into(),
                build: Some(10_454),
                n_ctx: Some(120_064),
                ..Default::default()
            },
            history::Entry {
                when: 2,
                model: "qwen3.8-27b-ud-q4_k_xl".into(),
                build: Some(10_630),
                n_ctx: Some(111_872),
                ..Default::default()
            },
        ];
        let text = render(&ReportInputs {
            date: date_from_epoch(1_787_700_000),
            os: "linux".into(),
            ram_mib: 64_000,
            gpus: vec![
                crate::core::discover::PhysicalGpu {
                    name: "NVIDIA GeForce RTX 3090 Ti".into(),
                    vram_mib: 24_111,
                    ids: vec!["CUDA0".into(), "Vulkan0".into()],
                    shared_memory: false,
                },
                crate::core::discover::PhysicalGpu {
                    name: "Intel(R) UHD Graphics 770".into(),
                    vram_mib: 48_012,
                    ids: vec!["Vulkan1".into()],
                    shared_memory: true,
                },
            ],
            build: Some(10_630),
            upstream: None,
            measurements: &m,
            trials: &trials,
            history: &hist,
            home: Some("/home/buck".into()),
        });
        assert!(
            text.contains("RTX 3090 Ti — 24111 MiB usable (backend views: CUDA0, Vulkan0)"),
            "one card, one line, conservative figure: {text}"
        );
        assert!(
            text.contains("iGPU") && text.contains("not counted as VRAM"),
            "shared memory never masquerades as VRAM: {text}"
        );
        assert!(!text.contains("48012"), "the phantom heap number must not appear");
        assert!(text.contains("| qwen3.8-27b-ud-q4_k_xl | 118016 |"));
        assert!(text.contains("b10454: 120064 -> b10630: 111872"), "{text}");
        assert!(text.contains("'~/models/x.gguf'"), "home sanitized: {text}");
        assert!(!text.contains("/home/buck"), "no raw home path anywhere");
        assert!(text.contains("2026-08-2"), "date renders: {text}");
    }

    #[test]
    fn civil_dates_are_correct() {
        assert_eq!(date_from_epoch(0), "1970-01-01");
        assert_eq!(date_from_epoch(86_400), "1970-01-02");
        assert_eq!(date_from_epoch(1_787_659_200), "2026-08-25");
    }
}
