//! The router server: preset generation and lifecycle for one long-lived
//! llama-server in router mode (see docs/spikes.md for the verified
//! behavior this module is built on).
//!
//! Ownership rule, inherited from llm_forge's launcher: we only ever signal
//! a process whose pid we recorded at spawn time AND whose /proc cmdline
//! still names our preset file. Anything else answering the port is
//! *external* — observed, reported, never touched.

use crate::core::library::{self, ModelFile};
use anyhow::{Context, Result, bail};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

/// Everything needed to run (or find) our router.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RouterConfig {
    pub server_bin: PathBuf,
    pub port: u16,
    pub preset_path: PathBuf,
    /// Max concurrently loaded models (`--models-max`). 1 is the right
    /// default on a single 24GB-class GPU; the router still *lists* every
    /// model and swaps on demand.
    pub models_max: u32,
}

// ─── preset generation ───────────────────────────────────────────────────────

/// Per-model knobs the app exposes; everything unset inherits `[*]` or
/// llama-server's own defaults (notably `--fit on` and `-ngl auto`).
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelOverrides {
    /// KV cache type; `None` inherits the global default (q8_0).
    pub cache_type_kv: Option<String>,
    /// Explicit context; `None` lets `--fit` decide (recommended).
    pub ctx: Option<u64>,
    /// Extra raw `key = value` INI lines for anything we don't model yet.
    pub extra: Vec<(String, String)>,
}

/// Render the router preset INI. Pure — writing it and telling the server to
/// reload are separate steps.
///
/// Defaults encode the north star for single-user agentic coding:
/// `np = 1` (one slot, so OpenCode gets the whole fitted context — instances
/// default to 4 slots sharing it) and `q8_0` KV cache (measured on this
/// machine: ~2x usable context vs f16 for the same VRAM).
pub fn render_preset(models: &[(String, &ModelFile, ModelOverrides)]) -> String {
    let mut out = String::from(
        "; Generated by llamacppcodeconf — edits are welcome but regeneration\n\
         ; overwrites this file; put keep-forever tweaks in the app instead.\n\
         version = 1\n\n\
         [*]\n\
         np = 1\n\
         cache-type-k = q8_0\n\
         cache-type-v = q8_0\n",
    );
    for (alias, model, ov) in models {
        out.push('\n');
        out.push_str(&format!("[{alias}]\n"));
        out.push_str(&format!("model = {}\n", model.path.display()));
        if let Some(kv) = &ov.cache_type_kv {
            out.push_str(&format!("cache-type-k = {kv}\ncache-type-v = {kv}\n"));
        }
        if let Some(c) = ov.ctx {
            out.push_str(&format!("c = {c}\n"));
        }
        for (k, v) in &ov.extra {
            out.push_str(&format!("{k} = {v}\n"));
        }
    }
    out
}

/// Default (alias, model, overrides) list for a scanned library: every model
/// with readable metadata, aliased via [`library::alias_suggestion`].
/// Duplicate aliases get a numeric suffix — never two sections one name.
pub fn default_entries(models: &[ModelFile]) -> Vec<(String, &ModelFile, ModelOverrides)> {
    let mut used = std::collections::HashSet::new();
    models
        .iter()
        .filter(|m| m.meta.is_some())
        .map(|m| {
            let base = library::alias_suggestion(m);
            let mut alias = base.clone();
            let mut n = 2;
            while !used.insert(alias.clone()) {
                alias = format!("{base}-{n}");
                n += 1;
            }
            (alias, m, ModelOverrides::default())
        })
        .collect()
}

// ─── state marker (ownership) ────────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct Marker {
    pub pid: u32,
    pub port: u16,
    pub preset_path: PathBuf,
    pub server_bin: PathBuf,
}

pub fn state_dir() -> PathBuf {
    std::env::var_os("XDG_STATE_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            std::env::home_dir()
                .unwrap_or_else(|| PathBuf::from("."))
                .join(".local/state")
        })
        .join("llamacppcodeconf")
}

fn marker_path(dir: &Path) -> PathBuf {
    dir.join("router.json")
}

pub fn read_marker(dir: &Path) -> Option<Marker> {
    serde_json::from_str(&std::fs::read_to_string(marker_path(dir)).ok()?).ok()
}

fn write_marker(dir: &Path, m: &Marker) -> Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(marker_path(dir), serde_json::to_string_pretty(m)?)
        .with_context(|| format!("writing {}", marker_path(dir).display()))
}

fn clear_marker(dir: &Path) {
    let _ = std::fs::remove_file(marker_path(dir));
}

/// Is the marker's process still alive AND still ours? "Ours" means its
/// /proc cmdline names both llama-server and our preset file — a recycled
/// pid fails this and is treated as gone.
pub fn marker_is_live(m: &Marker) -> bool {
    let Ok(cmdline) = std::fs::read(format!("/proc/{}/cmdline", m.pid)) else {
        return false;
    };
    let cmdline = String::from_utf8_lossy(&cmdline).replace('\0', " ");
    cmdline_matches(&cmdline, &m.preset_path)
}

fn cmdline_matches(cmdline: &str, preset: &Path) -> bool {
    cmdline.contains("llama-server") && cmdline.contains(&preset.display().to_string())
}

/// Find any process running llama-server with OUR preset file — covers the
/// systemd-user-unit case, where the marker (written by whichever process
/// spawned the server) doesn't exist in this app's state. Running our
/// generated preset is the ownership credential; an arbitrary llama-server
/// never matches.
pub fn find_preset_process(preset: &Path) -> Option<u32> {
    let proc = std::fs::read_dir("/proc").ok()?;
    for e in proc.flatten() {
        let name = e.file_name();
        let Some(pid) = name.to_str().and_then(|s| s.parse::<u32>().ok()) else {
            continue;
        };
        if let Ok(cmdline) = std::fs::read(e.path().join("cmdline")) {
            let cmdline = String::from_utf8_lossy(&cmdline).replace('\0', " ");
            if cmdline_matches(&cmdline, preset) {
                return Some(pid);
            }
        }
    }
    None
}

// ─── lifecycle ───────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Serialize)]
#[serde(tag = "state", rename_all = "snake_case")]
pub enum RouterState {
    /// Nothing answers the port and no live marker.
    Down,
    /// Our router is up; per-model statuses included.
    Ours { models: Vec<RouterModel> },
    /// Something we didn't start answers the port. Observed, never touched.
    External { detail: String },
    /// Marker says ours but the port isn't answering (yet / anymore).
    Trouble { detail: String },
}

#[derive(Debug, Clone, PartialEq, Serialize)]
pub struct RouterModel {
    pub id: String,
    /// "loaded" | "loading" | "unloaded" | "sleeping"; failed loads become
    /// "failed(<exit>)" so the UI never mistakes them for merely-unloaded.
    pub status: String,
    /// Where the router got this model: "preset" (ours) or "cache"
    /// (LLAMA_CACHE downloads the router discovered on its own).
    pub source: Option<String>,
    /// Fingerprint of the effective child args the router would launch this
    /// model with — the "did its config change?" half of measurement
    /// staleness (the other half is the environment fingerprint).
    pub args_fp: Option<String>,
}

/// Drop volatile flag pairs from a child-args list before fingerprinting:
/// the router stamps `--port 0` on unloaded entries but the *actual*
/// ephemeral port after a load, so including it would mark every model
/// stale the moment it had ever been loaded.
fn stable_args<'a>(args: &[&'a str]) -> Vec<&'a str> {
    let mut out = Vec::with_capacity(args.len());
    let mut skip_value = false;
    for a in args {
        if skip_value {
            skip_value = false;
            continue;
        }
        if *a == "--port" {
            skip_value = true;
            continue;
        }
        out.push(*a);
    }
    out
}

/// FNV-1a 64-bit, hex. Stable across runs and Rust versions (unlike
/// DefaultHasher), which is what a persisted fingerprint requires.
pub fn fnv(s: &str) -> String {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in s.as_bytes() {
        h ^= u64::from(*b);
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{h:016x}")
}

/// Parse the router's `GET /models` response (verified shape: spike 1).
pub fn parse_models_response(body: &serde_json::Value) -> Vec<RouterModel> {
    body.get("data")
        .and_then(|d| d.as_array())
        .map(|models| {
            models
                .iter()
                .filter_map(|m| {
                    let id = m.get("id")?.as_str()?.to_string();
                    let st = m.get("status")?;
                    let mut status = st.get("value")?.as_str()?.to_string();
                    if st.get("failed").and_then(|f| f.as_bool()) == Some(true) {
                        let code = st.get("exit_code").and_then(|c| c.as_i64()).unwrap_or(-1);
                        status = format!("failed({code})");
                    }
                    let source = m.get("source").and_then(|s| s.as_str()).map(String::from);
                    let args_fp = st
                        .get("args")
                        .and_then(|a| a.as_array())
                        .map(|args| {
                            let strs: Vec<&str> =
                                args.iter().filter_map(|v| v.as_str()).collect();
                            fnv(&stable_args(&strs).join(" "))
                        });
                    Some(RouterModel {
                        id,
                        status,
                        source,
                        args_fp,
                    })
                })
                .collect()
        })
        .unwrap_or_default()
}

fn fetch_models(port: u16) -> Result<Vec<RouterModel>> {
    let body: serde_json::Value = ureq::get(&format!("http://127.0.0.1:{port}/models"))
        .timeout(std::time::Duration::from_secs(5))
        .call()
        .context("router /models not answering")?
        .into_json()
        .context("router /models returned non-JSON")?;
    Ok(parse_models_response(&body))
}

/// What is true about our configured port right now. "Ours" = the marker we
/// wrote at spawn is live, OR some process (e.g. a systemd user unit) is
/// running llama-server with our preset file.
pub fn status(dir: &Path, cfg: &RouterConfig) -> RouterState {
    let ours = read_marker(dir).is_some_and(|m| marker_is_live(&m))
        || find_preset_process(&cfg.preset_path).is_some();
    match fetch_models(cfg.port) {
        Ok(models) if ours => RouterState::Ours { models },
        Ok(models) => RouterState::External {
            detail: format!(
                "port {} serves {} model(s) but we have no record of starting it",
                cfg.port,
                models.len()
            ),
        },
        Err(e) if ours => RouterState::Trouble {
            detail: format!("our router process is alive but: {e:#}"),
        },
        Err(_) => RouterState::Down,
    }
}

/// Start the router. Refuses if the port already answers (ours or not) or a
/// live marker exists — "start" never doubles as "restart".
pub fn start(dir: &Path, cfg: &RouterConfig) -> Result<u32> {
    if let Some(m) = read_marker(dir)
        && marker_is_live(&m)
    {
        bail!("our router is already running (pid {})", m.pid);
    }
    if fetch_models(cfg.port).is_ok() {
        bail!(
            "port {} is already serving — a server we didn't start; refusing to interfere",
            cfg.port
        );
    }
    std::fs::create_dir_all(dir)?;
    let log = std::fs::File::create(dir.join("router.log")).context("creating router.log")?;
    let child = std::process::Command::new(&cfg.server_bin)
        .arg("--models-preset")
        .arg(&cfg.preset_path)
        .arg("--host")
        .arg("127.0.0.1")
        .arg("--port")
        .arg(cfg.port.to_string())
        .arg("--models-max")
        .arg(cfg.models_max.to_string())
        .stdin(std::process::Stdio::null())
        .stdout(log.try_clone().context("cloning log handle")?)
        .stderr(log)
        .spawn()
        .with_context(|| format!("spawning {}", cfg.server_bin.display()))?;
    let pid = child.id();
    write_marker(
        dir,
        &Marker {
            pid,
            port: cfg.port,
            preset_path: cfg.preset_path.clone(),
            server_bin: cfg.server_bin.clone(),
        },
    )?;
    Ok(pid)
}

/// Stop our router: SIGTERM, but only to a pid whose cmdline names our
/// preset — the marker pid normally, or a preset-matched process (systemd
/// case) when no marker exists. External servers are untouchable by design.
pub fn stop(dir: &Path, preset: &Path) -> Result<()> {
    let pid = match read_marker(dir) {
        Some(m) if marker_is_live(&m) => m.pid,
        Some(m) => {
            clear_marker(dir);
            match find_preset_process(preset) {
                Some(pid) => pid,
                None => bail!(
                    "our router (pid {}) is already gone; cleared the stale record",
                    m.pid
                ),
            }
        }
        None => find_preset_process(preset)
            .ok_or_else(|| anyhow::anyhow!("no llama-server running our preset found"))?,
    };
    let ok = std::process::Command::new("kill")
        .arg(pid.to_string())
        .status()
        .context("sending SIGTERM")?
        .success();
    if !ok {
        bail!("kill {pid} failed");
    }
    // Give it a moment; router children get llama-server's stop-timeout.
    for _ in 0..50 {
        if find_preset_process(preset).is_none() {
            clear_marker(dir);
            return Ok(());
        }
        std::thread::sleep(std::time::Duration::from_millis(100));
    }
    bail!("router (pid {pid}) did not exit within 5s; not escalating automatically")
}

// ─── calibration ─────────────────────────────────────────────────────────────
//
// The context a model *actually* gets is decided by `--fit` at load time and
// is only knowable by loading the model (spike 2: 27B-Q5 settled at 72,960
// with q8_0 KV where the GGUF header says 262,144). Calibration loads each
// preset model once, records the settled n_ctx, and unloads it. Results are
// keyed by alias and kept in the state dir; opencode sync refuses to guess
// and only writes measured numbers.

/// One calibration result — success (`n_ctx` measured) or remembered
/// failure (`error`), stamped with fingerprints so staleness is detectable.
/// Old measurement files (bare `{"n_ctx": N}`) still parse; their missing
/// fingerprints read as "stale", which re-measures them — the right thing.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Measurement {
    /// The context `--fit` settled on. `None` = the load failed.
    pub n_ctx: Option<u64>,
    /// Why the load failed, when it did.
    pub error: Option<String>,
    /// Fingerprint of the model's effective launch args at measurement time.
    pub args_fp: Option<String>,
    /// Fingerprint of the environment (server build + devices).
    pub env_fp: Option<String>,
}

impl Default for Measurement {
    fn default() -> Self {
        Self {
            n_ctx: None,
            error: None,
            args_fp: None,
            env_fp: None,
        }
    }
}

impl Measurement {
    /// Fresh = measured (or failed) under exactly this config + environment.
    pub fn is_fresh(&self, current_args_fp: Option<&str>, env_fp: &str) -> bool {
        (self.n_ctx.is_some() || self.error.is_some())
            && self.env_fp.as_deref() == Some(env_fp)
            && self.args_fp.as_deref() == current_args_fp
            && current_args_fp.is_some()
    }
}

pub type Measurements = std::collections::BTreeMap<String, Measurement>;

fn measurements_path(dir: &Path) -> PathBuf {
    dir.join("measurements.json")
}

pub fn read_measurements(dir: &Path) -> Measurements {
    std::fs::read_to_string(measurements_path(dir))
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default()
}

pub fn write_measurements(dir: &Path, m: &Measurements) -> Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(measurements_path(dir), serde_json::to_string_pretty(m)?)
        .with_context(|| format!("writing {}", measurements_path(dir).display()))
}

/// Settled context for one model, measured without any long-blocking
/// request: explicit load → poll status until loaded/failed (cold-cache
/// loads of 20GB files can take minutes; a hanging GET would trip HTTP
/// timeouts and the router's request-scoped kill paths) → read `/props`
/// with autoload off.
pub fn fetch_settled_ctx(port: u16, model: &str) -> Result<u64> {
    load_model(port, model)?;
    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(600);
    loop {
        let status = fetch_models(port)?
            .into_iter()
            .find(|m| m.id == model)
            .map(|m| m.status)
            .ok_or_else(|| anyhow::anyhow!("{model} vanished from /models during load"))?;
        match status.as_str() {
            "loaded" | "sleeping" => break,
            s if s.starts_with("failed") => {
                bail!("{model} did not load: {s} (see router.log)")
            }
            _ if std::time::Instant::now() > deadline => {
                let _ = unload_model(port, model); // don't leave it wedged
                bail!("{model} still not loaded after 600s; gave up")
            }
            _ => std::thread::sleep(std::time::Duration::from_secs(1)),
        }
    }
    let url = format!(
        "http://127.0.0.1:{port}/props?model={}&autoload=false",
        urlencode(model)
    );
    let body: serde_json::Value = ureq::get(&url)
        .timeout(std::time::Duration::from_secs(15))
        .call()
        .with_context(|| format!("/props for {model}"))?
        .into_json()?;
    body.get("default_generation_settings")
        .and_then(|g| g.get("n_ctx"))
        .and_then(|n| n.as_u64())
        .ok_or_else(|| anyhow::anyhow!("no n_ctx in /props for {model}"))
}

/// Request a load (async server-side; poll `status` to watch it land).
pub fn load_model(port: u16, model: &str) -> Result<()> {
    ureq::post(&format!("http://127.0.0.1:{port}/models/load"))
        .timeout(std::time::Duration::from_secs(30))
        .send_json(serde_json::json!({ "model": model }))
        .with_context(|| format!("loading {model}"))?;
    Ok(())
}

pub fn unload_model(port: u16, model: &str) -> Result<()> {
    ureq::post(&format!("http://127.0.0.1:{port}/models/unload"))
        .timeout(std::time::Duration::from_secs(30))
        .send_json(serde_json::json!({ "model": model }))
        .with_context(|| format!("unloading {model}"))?;
    Ok(())
}

fn urlencode(s: &str) -> String {
    s.bytes()
        .map(|b| match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                (b as char).to_string()
            }
            other => format!("%{other:02X}"),
        })
        .collect()
}

/// Measure preset models one at a time (load → read settled ctx → unload),
/// updating stored measurements as it goes. **Incremental by default**:
/// models whose stored measurement is fresh (same effective args, same
/// build/devices) are skipped — including remembered *failures*, so a model
/// this build can't load doesn't re-fail on every run. `force` re-measures
/// everything. `progress` narrates each decision.
pub fn calibrate(
    dir: &Path,
    port: u16,
    env_fp: &str,
    force: bool,
    progress: &mut dyn FnMut(String),
) -> Result<Measurements> {
    // Preset models AND the router's own HF cache downloads ("cache" source
    // — e.g. models pulled by `llama-server -hf` or vendor tools). Both are
    // servable through the router, so both deserve measurement; anything
    // else (a future source we don't know) is left alone.
    let models: Vec<_> = fetch_models(port)?
        .into_iter()
        .filter(|m| matches!(m.source.as_deref(), Some("preset") | Some("cache")))
        .collect();
    if models.is_empty() {
        bail!("router lists no preset or cache models to calibrate");
    }
    let mut out = read_measurements(dir);
    let total = models.len();
    for (i, m) in models.iter().enumerate() {
        let n = i + 1;
        if !force
            && let Some(stored) = out.get(&m.id)
            && stored.is_fresh(m.args_fp.as_deref(), env_fp)
        {
            let what = match (&stored.n_ctx, &stored.error) {
                (Some(ctx), _) => format!("ctx {ctx}"),
                (None, Some(_)) => "known load failure".to_string(),
                _ => unreachable!("is_fresh requires one of them"),
            };
            progress(format!("[{n}/{total}] {} — fresh ({what}), skipping", m.id));
            continue;
        }
        progress(format!("[{n}/{total}] measuring {} (loads the model)…", m.id));
        // First failure gets one retry after a settle: unloads are async,
        // so a load can race a predecessor still releasing VRAM and fail
        // (or fit against less memory than it will really have).
        let result = fetch_settled_ctx(port, &m.id).or_else(|first_err| {
            progress(format!(
                "[{n}/{total}] {} failed once ({first_err:#}); settling 5s and retrying…",
                m.id
            ));
            std::thread::sleep(std::time::Duration::from_secs(5));
            fetch_settled_ctx(port, &m.id).map_err(|e| e.context("retry also failed"))
        });
        let measurement = match result {
            Ok(n_ctx) => Measurement {
                n_ctx: Some(n_ctx),
                error: None,
                args_fp: m.args_fp.clone(),
                env_fp: Some(env_fp.to_string()),
            },
            Err(e) => {
                progress(format!("[{n}/{total}] {} failed: {e:#}", m.id));
                Measurement {
                    n_ctx: None,
                    error: Some(format!("{e:#}")),
                    args_fp: m.args_fp.clone(),
                    env_fp: Some(env_fp.to_string()),
                }
            }
        };
        out.insert(m.id.clone(), measurement);
        write_measurements(dir, &out)?; // persist per model — a mid-run
        // failure keeps everything measured so far
        let _ = unload_model(port, &m.id);
        wait_until_not_loaded(port, &m.id, std::time::Duration::from_secs(30));
    }
    Ok(out)
}

/// Block until the router no longer reports `model` as loaded/loading —
/// i.e. its VRAM is actually back. Measurements taken without this race
/// the previous model's teardown and come out low (or fail outright).
fn wait_until_not_loaded(port: u16, model: &str, timeout: std::time::Duration) {
    let deadline = std::time::Instant::now() + timeout;
    while std::time::Instant::now() < deadline {
        match fetch_models(port) {
            Ok(models) => {
                let busy = models
                    .iter()
                    .any(|m| m.id == model && matches!(m.status.as_str(), "loaded" | "loading"));
                if !busy {
                    return;
                }
            }
            Err(_) => return, // router gone — nothing to wait for
        }
        std::thread::sleep(std::time::Duration::from_millis(500));
    }
}

/// Ask a running router to re-read its model sources (`/models?reload=1`,
/// verified in spike 1) — how preset edits land without a restart.
pub fn reload(port: u16) -> Result<Vec<RouterModel>> {
    let body: serde_json::Value = ureq::get(&format!("http://127.0.0.1:{port}/models?reload=1"))
        .timeout(std::time::Duration::from_secs(10))
        .call()
        .context("router reload failed")?
        .into_json()?;
    Ok(parse_models_response(&body))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::library::Source;

    fn model(path: &str) -> ModelFile {
        ModelFile {
            path: PathBuf::from(path),
            file_size: 0,
            source: Source::Shelf,
            meta: Some(Default::default()),
        }
    }

    #[test]
    fn preset_has_coding_agent_defaults_and_per_model_sections() {
        let m1 = model("/models/a.gguf");
        let m2 = model("/models/b.gguf");
        let entries = vec![
            ("alpha".to_string(), &m1, ModelOverrides::default()),
            (
                "beta".to_string(),
                &m2,
                ModelOverrides {
                    cache_type_kv: Some("f16".into()),
                    ctx: Some(16384),
                    extra: vec![("fit-target".into(), "2048".into())],
                },
            ),
        ];
        let ini = render_preset(&entries);
        assert!(ini.contains("version = 1"));
        assert!(ini.contains("[*]\nnp = 1\ncache-type-k = q8_0"));
        assert!(ini.contains("[alpha]\nmodel = /models/a.gguf\n"));
        // beta overrides the global KV type and pins ctx.
        assert!(ini.contains("[beta]"));
        assert!(ini.contains("cache-type-k = f16"));
        assert!(ini.contains("c = 16384"));
        assert!(ini.contains("fit-target = 2048"));
    }

    #[test]
    fn duplicate_aliases_get_suffixes_not_collisions() {
        let m1 = model("/x/Same-Name.gguf");
        let m2 = model("/y/Same-Name.gguf");
        let models = vec![m1, m2];
        let entries = default_entries(&models);
        assert_eq!(entries[0].0, "same-name");
        assert_eq!(entries[1].0, "same-name-2");
    }

    #[test]
    fn metaless_models_are_excluded_from_the_preset() {
        let mut broken = model("/x/broken.gguf");
        broken.meta = None;
        assert!(default_entries(&[broken]).is_empty());
    }

    #[test]
    fn parses_models_response_including_failures() {
        let body = serde_json::json!({"data": [
            {"id": "good", "status": {"value": "loaded", "args": []}},
            {"id": "bad", "status": {"value": "unloaded", "failed": true, "exit_code": 1}},
            {"id": "pending", "status": {"value": "loading"}}
        ]});
        let models = parse_models_response(&body);
        assert_eq!(models.len(), 3);
        assert_eq!(models[0].status, "loaded");
        assert_eq!(models[1].status, "failed(1)");
        assert_eq!(models[2].status, "loading");
    }

    #[test]
    fn fnv_is_stable_and_discriminating() {
        assert_eq!(fnv("abc"), fnv("abc"));
        assert_ne!(fnv("abc"), fnv("abd"));
        assert_eq!(fnv(""), "cbf29ce484222325");
    }

    #[test]
    fn args_fingerprint_comes_from_status_args() {
        let body = serde_json::json!({"data": [
            {"id": "a", "status": {"value": "unloaded", "args": ["llama-server", "-c", "4096"]}},
            {"id": "b", "status": {"value": "unloaded"}}
        ]});
        let models = parse_models_response(&body);
        assert_eq!(models[0].args_fp.as_deref(), Some(fnv("llama-server -c 4096").as_str()));
        assert!(models[1].args_fp.is_none());
    }

    #[test]
    fn ephemeral_port_does_not_change_the_fingerprint() {
        let fp = |port: &str| {
            let body = serde_json::json!({"data": [
                {"id": "a", "status": {"value": "unloaded",
                    "args": ["llama-server", "--port", port, "-c", "4096"]}}
            ]});
            parse_models_response(&body)[0].args_fp.clone().unwrap()
        };
        assert_eq!(fp("0"), fp("53001"), "load-assigned port must not mark models stale");
        let no_port = {
            let body = serde_json::json!({"data": [
                {"id": "a", "status": {"value": "unloaded", "args": ["llama-server", "-c", "4096"]}}
            ]});
            parse_models_response(&body)[0].args_fp.clone().unwrap()
        };
        assert_eq!(fp("0"), no_port);
    }

    #[test]
    fn freshness_requires_matching_fingerprints() {
        let m = Measurement {
            n_ctx: Some(1000),
            error: None,
            args_fp: Some("aaaa".into()),
            env_fp: Some("eeee".into()),
        };
        assert!(m.is_fresh(Some("aaaa"), "eeee"));
        assert!(!m.is_fresh(Some("bbbb"), "eeee"), "args changed → stale");
        assert!(!m.is_fresh(Some("aaaa"), "ffff"), "env changed → stale");
        assert!(!m.is_fresh(None, "eeee"), "unknown current args → stale");

        let failed = Measurement {
            n_ctx: None,
            error: Some("boom".into()),
            args_fp: Some("aaaa".into()),
            env_fp: Some("eeee".into()),
        };
        assert!(failed.is_fresh(Some("aaaa"), "eeee"), "failures are remembered");
    }

    #[test]
    fn old_measurement_files_parse_as_stale() {
        let old: Measurements =
            serde_json::from_str(r#"{"alias": {"n_ctx": 72960}}"#).unwrap();
        let m = &old["alias"];
        assert_eq!(m.n_ctx, Some(72960));
        assert!(
            !m.is_fresh(Some("anything"), "env"),
            "no fingerprints → re-measure"
        );
    }

    #[test]
    fn marker_roundtrip_and_pid_recycling_safety() {
        let dir = tempfile::tempdir().unwrap();
        let m = Marker {
            pid: 1, // pid 1 exists but is init, not llama-server
            port: 18080,
            preset_path: PathBuf::from("/tmp/p.ini"),
            server_bin: PathBuf::from("/usr/bin/llama-server"),
        };
        write_marker(dir.path(), &m).unwrap();
        let back = read_marker(dir.path()).unwrap();
        assert_eq!(back.pid, 1);
        // init's cmdline doesn't mention llama-server or our preset →
        // a recycled pid is "not ours", never a kill target.
        assert!(!marker_is_live(&back));
    }

    #[test]
    fn cmdline_matching_requires_both_binary_and_preset() {
        let preset = Path::new("/home/u/.config/app/router.ini");
        assert!(cmdline_matches(
            "/opt/llama-server --models-preset /home/u/.config/app/router.ini",
            preset
        ));
        assert!(!cmdline_matches("/opt/llama-server -m other.gguf", preset));
        assert!(!cmdline_matches(
            "vim /home/u/.config/app/router.ini",
            preset
        ));
    }
}
